apiVersion: v1
kind: Pod
metadata:
  name: kurtis-security-context-demo-priv-esca
spec:
  containers:
  - name: sec-ctx-demo
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-sock-volume
  volumes:
  - name: docker-sock-volume
    hostPath:
      # directory location on host
      path: /var/run/docker.sock
      # this field is optional
      type: 
