apiVersion: v1
kind: Pod
metadata:
  name: kurtis-security-context-demo-priv-esca
spec:
  containers:
  - name: sec-ctx-demo
    image: teamnautilus/diamorphine_demo:latest
    command: [ "sh", "-c", "/run.sh && while true; do echo alive; sleep 2; done" ]
    securityContext:
      privileged: true
