apiVersion: v1
kind: Pod
metadata:
  name: kurtis-security-context-demo-priv-esca
spec:
  volumes:
  - name: sec-ctx-vol
  containers:
  - name: sec-ctx-demo
    volumeMounts:
    - name: sec-ctx-vol
      mountPath: /data/demo
