apiVersion: v1
kind: Pod
metadata:
  name: kurtis-security-context-demo-priv-esca
spec:
  hostNetwork: false
  hostPID: false
  hostIPC: false
  containers:
  - name: sec-ctx-demo
    image: nginx:latest
    command: [ "sh", "-c", "sleep 1h" ]
